development: &development
 adapter: mysql2
 strict: false
 database: minion_development_dev
 username: root
 host: localhost
 password:

test: &test
 adapter: mysql2
 strict: false
 database: minione_development_test
 username: root
 host: localhost
 password:

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: minion_development